<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="SamsonEdward" name="TestNGTestcases.EnableAnnotation" tests="8" failures="0" timestamp="16 May 2020 05:37:34 GMT" time="0.979" errors="1">
  <testcase name="show1" time="0.003" classname="TestNGTestcases.EnableAnnotation"/>
  <testcase name="methodfail" time="0.031" classname="TestNGTestcases.EnableAnnotation"/>
  <testcase name="show" time="0.010" classname="TestNGTestcases.EnableAnnotation"/>
  <testcase name="timeTestOne" time="0.513" classname="TestNGTestcases.EnableAnnotation">
    <error type="org.testng.internal.thread.ThreadTimeoutException" message="Method TestNGTestcases.EnableAnnotation.timeTestOne() didn&#039;t finish within the time-out 500">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method TestNGTestcases.EnableAnnotation.timeTestOne() didn't finish within the time-out 500
at java.util.concurrent.FutureTask.finishCompletion(Unknown Source)
at java.util.concurrent.FutureTask.setException(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- timeTestOne -->
  <testcase name="timeTestTwo" time="0.406" classname="TestNGTestcases.EnableAnnotation"/>
  <testcase name="show2" time="0.011" classname="TestNGTestcases.EnableAnnotation"/>
  <testcase name="error" time="0.003" classname="TestNGTestcases.EnableAnnotation"/>
  <testcase name="alwaysruntrue" time="0.002" classname="TestNGTestcases.EnableAnnotation"/>
</testsuite> <!-- TestNGTestcases.EnableAnnotation -->
